--- 
project_name: Linguistics
project_homepage: http://deveiate.org/projects/Linguistics/
project_summary: a framework for building linguistic utilities for Ruby objects
project_description: |-
  in any language. It includes a generic language-independant front end, a
  module for mapping language codes into language names, and a module which
  contains various English-language utilities.
project_pubhost: deveiate
project_pubdir: /usr/local/www/public/code
gem_pubhost: rubygems.org
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
release_smtphost: mail.faeriemud.org
post_install_message: ""
authors: 
  Michael Granger: ged@FaerieMUD.org
project_dependencies: {}

dev_dependencies: 
  rspec: ">=2.0.0"
  wordnet: ">=0.0.5"
  linkparser: ">=1.0.6"
project_requirements: {}

additional_pkgfiles: 
- examples/*.rb
- README.english
excluded_pkgfiles: []

version_file: linguistics.rb
